export const BET_SELECTED = 'BET_SELECTED';
export const DEFAULT_STAKE = 'DEFAULT_STAKE';
export const REMOTE_BET = 'REMOTE_BET';
export const INPUT_DEFAULT_STAKE = 'INPUT_DEFAULT_STAKE';
export const DEVICE_TYPE = 'DEVICE_TYPE';
export const SELECT_TAB = 'SELECT_TAB';